### ISSUE TITLE
fetch url will use the first/last match folder 

### ISSUE THREAD

**Issue by liuhangbin** [restraint-harness/restraint#272] opened 2022-07-12 02:47 UTC
If a sub-test name is same with another test name. The fetch url will use the last match folder instead of total matches. e.g.

```
total_tests
    |- kselftests
    |- livepatch/kselftests
```

If I try to fetch kselftest like

`fetch url="https://repo_url/total_tests/-/archive/main/toal_tests-main.zip#kselftests"`, restraint will fetch `livepatch/kselftests` instead of `kselftests`.

**Comment by sztsian** [comment] 2022-10-13 09:13
This affects me as well. When we run our case `general/include`, it will try to install both `general/include` and `filesystems/general/include`. However, the dependency of the later one cannot be satisfied in my test, so it blocks my testing.

I hope this can be solved otherwise we will need to switch back to beah harness.

**Comment by p3ck** [comment] 2022-10-18 13:29
I can reproduce this issue and I'm looking at how best to fix it.

**Comment by p3ck** [comment] 2022-10-18 14:27
a workaround you can use is to specify the fragment with ./ in the beginning..

`fetch url="https://repo_url/total_tests/-/archive/main/toal_tests-main.zip#./kselftests"`

**Comment by p3ck** [comment] 2022-10-18 14:48
Can either of you provide the actual fetch url that is failing for you?  Assuming your tests are opensource and available on the internet?  I just want to make sure I'm not missing a corner case.

Thanks

**Comment by bgoncalv** [comment] 2022-10-18 14:50
The tests are on https://gitlab.com/redhat/centos-stream/tests/kernel/kernel-tests

**Comment by bgoncalv** [comment] 2022-10-19 08:57
@p3ck btw, the problem with repoRequires: from [comment](https://github.com/restraint-harness/restraint/issues/272#issuecomment-1277291842) will also be addressed or this is different issue and we need to report it separately?

**Comment by cbouchar** [comment] 2022-10-24 18:40
@bgoncalv I'm working on this issue and reporRequires cause it's in the same vicinity of code. I believe these issues are related to a single issue.  @p3ck Keeping Bill in the loop since we're discussed this.

**Comment by idorax** [comment] 2023-02-03 08:24
Hi @cbouchar, is your patch ready for this issue? If it's not 100% ready, please let me know if you need my effort so as to save your time.

**Comment by cbouchar** [comment] 2023-02-03 12:42
@idorax I'm working on releasing code.  I have dependencies on other people (for a number of reasons) which is slowing down the process.

**Comment by cbouchar** [comment] 2023-02-03 13:21
Closing this issue as changeset has been committed pending restraint release.

**Comment by cbouchar** [comment] 2023-03-13 19:01
Plan to remove the fix for providing precision in selecting subdirectories for
repoRequires.  Without the fix (pull 275), the match behaves more like a
'contains' operation rather than a precise directory match.  With release 0.4.2
which contains pull 275, users complained of breakages.

In inspecting the user selection data, this selection data would also have to
be precise which is not the case for all users.  It was presented to a
group of users if it would be best for the users to provide more precise
directory names OR apply the fixes and spend time analyzing and fixing all
user's data to see how they can make it more precise.
Since this latter option will affect testing schedules, the users chose to
back out the fix and user will instead provide concise directory names.

How can users provide more precise directory names?  Instead of
repoRequires=include, users instead can define repoRequires=common/include
and rename the 'include' directory to 'common/include'.  So if the tree was
defined as follows, there should be no ambiguity.

my-test-repo
     uncommon-dir
         include
     common
         include
     dir-with-code-to-execute
         metadata contains repoRequires=common/include

If at a later time, users decide they need precise directory selection by
restraint, the following are the patches needed in this order.

* Provides subdirectory match (repo_branch excluded in selection).
  https://github.com/restraint-harness/restraint/pull/275
* This allows the options of including repo_branch in selection.
  https://github.com/restraint-harness/restraint/pull/289

The code that's affected by the changes supports both
`repoRequires` function AND `fetch` function which is when
repo_branch selection filter comes into the picture by some users
but not all user.

**Closed by cbouchar** 2023-03-13 19:01 UTC
